name: weather_app
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  flutter_svg: ^1.0.3
  provider: ^6.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.0.1
  dartz: ^0.10.1
  equatable: ^2.0.3
  internet_connection_checker: ^0.0.1+3
  geolocator: ^8.2.0
  intl: ^0.17.0
  pull_to_refresh: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - config/
    - assets/images/
    - assets/


  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Black.ttf
          weight: 900
        - asset: fonts/Avenir-Medium.ttf
          weight: 500
    - family: SFProDisplay
      fonts:
        - asset: fonts/SFProDisplay-Regular.ttf
          weight: 400
    - family: SFProText
      fonts:
        - asset: fonts/SFProText-Regular.ttf
          weight: 400
